In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4107, 9724, 3256, 2360],
 [4107, 9724, 3256, 9384],
 [4107, 8773, 3256, 5670],
 [1771, 9917, 6653, 6251, 9946],
 [1771, 9917, 6653, 6251, 7549],
 [384, 4107, 4356, 3256, 7532],
 [3549, 9857, 177, 6251]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4107 9724 3256 2360]
 [   0    0    0    0 4107 9724 3256 9384]
 [   0    0    0    0 4107 8773 3256 5670]
 [   0    0    0 1771 9917 6653 6251 9946]
 [   0    0    0 1771 9917 6653 6251 7549]
 [   0    0    0  384 4107 4356 3256 7532]
 [   0    0    0    0 3549 9857  177 6251]]


In [10]:
## feature representation
dim=10

In [20]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length, input_shape=(sent_length,)))  # Add input_shape here
model.compile('adam', 'mse')
model.summary()


d:\MyProjects\A.I-Projects\Deep-Learning-For-NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[[-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.03222125, -0.01478894, -0.03294754, -0.02469844,
          0.01311243, -0.00884435,  0.018358  , -0.04924586,
         -0.00311322,  0.04575894],
        [ 0.01520671,  0.01002123, -0.01267647,  0.02424352,
          0.00701278,  0.02762133, -0.0172555 , -0.04841119,
          0.01458118, -0.00011859],
        [-0.02380837,  0.03711459,  0.01610864, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 4107, 9724, 3256, 2360], dtype=int32)

In [24]:
model.predict(np.array([embedded_docs[0]]))  # Correct: Shape becomes (1, 8)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.01275361,  0.02770095, -0.02236177, -0.00609015,
         -0.04809893,  0.0128369 , -0.02130773, -0.01091049,
         -0.02133039,  0.04136227],
        [-0.03222125, -0.01478894, -0.03294754, -0.02469844,
          0.01311243, -0.00884435,  0.018358  , -0.04924586,
         -0.00311322,  0.04575894],
        [ 0.01520671,  0.01002123, -0.01267647,  0.02424352,
          0.00701278,  0.02762133, -0.0172555 , -0.04841119,
          0.01458118, -0.00011859],
        [-0.02380837,  0.03711459,  0.01610864, -0.0